<?php
echo '<?php';
echo '/**';
echo '* Requires the "PHP Email Form" library';
echo '* The "PHP Email Form" library is available only in the pro version of the template';
echo '* The library should be uploaded to: vendor/php-email-form/php-email-form.php';
echo '* For more info and help: https://bootstrapmade.com/php-email-form/';
echo '*/';
echo '';
echo '// Replace contact@example.com with your real receiving email address';
echo '$receiving_email_address = 'ishan17vk@gmail.com';';
echo '';
echo 'if( file_exists($php_email_form = '../assets/vendor/php-email-form/php-email-form.php' )) {';
echo 'include( $php_email_form );';
echo '} else {';
echo 'die( 'Unable to load the "PHP Email Form" Library!');';
echo '}';
echo '';
echo '$contact = new PHP_Email_Form;';
echo '$contact->ajax = true;';
echo '';
echo '$contact->to = $receiving_email_address;';
echo '$contact->from_name = $_POST['name'];';
echo '$contact->from_email = $_POST['email'];';
echo '$contact->subject = $_POST['subject'];';
echo '';
echo '// Uncomment below code if you want to use SMTP to send emails. You need to enter your correct SMTP credentials';
echo '/*';
echo '$contact->smtp = array(';
echo ''host' => 'example.com',';
echo ''username' => 'example',';
echo ''password' => 'pass',';
echo ''port' => '587'';
echo ');';
echo '*/';
echo '';
echo '$contact->add_message( $_POST['name'], 'From');';
echo '$contact->add_message( $_POST['email'], 'Email');';
echo '$contact->add_message( $_POST['message'], 'Message', 10);';
echo '';
echo 'echo $contact->send();';
echo '?>';
?>